name: CI

on:
  push:
    branches:
      - foo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
        azure-devops-project-url: 'https://dev.azure.com/cityofhelsinki/helsinki-infra/'
        # Name of the Azure Pipline to be triggered
        azure-pipeline-name: 'helsinki-infra'
        # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
